whitelist_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
#  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
#!  - discouraged_object_literal
#!  - discouraged_optional_boolean
#!  - discouraged_optional_collection
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
#!  - explicit_acl
#  - explicit_enum_raw_value
  - explicit_init
#  - explicit_top_level_acl
#  - explicit_type_interface
#  - extension_access_modifier
  - fallthrough
  - fatal_error_message
#  - file_header
#  - file_length
#!  - file_name
#  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - for_where
# Disabled in test target only:
  - force_cast
# Disabled in test target only:
  - force_try
# Disabled in test target only:
  - force_unwrapping
#  - function_body_length
#  - function_default_parameter_at_end
#  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicit_return
# Disabled in test target only:
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
# Disabled in test target only:
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
#  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
#!  - missing_docs
#  - modifier_order
#  - multiline_arguments
#  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
#  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
#  - nesting
  - nimble_operator
#  - no_extension_access_modifier
  - no_fallthrough_only
#  - no_grouping_extension
  - no_space_in_method_call
#  - notification_center_detachment
#  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
#  - number_separator
#  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
#!  - override_in_extension
#  - pattern_matching_keywords
#!  - prefixed_toplevel_constant
  - private_action
#  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
#!  - quick_discouraged_focused_test
#!  - quick_discouraged_pending_test
#  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
#  - redundant_type_annotation
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
#  - sorted_imports
  - statement_position
#  - strict_fileprivate
  - strong_iboutlet
  - superfluous_disable_command
  - switch_case_alignment
#  - switch_case_on_newline
  - syntactic_sugar
#  - todo
#  - trailing_closure
#  - trailing_comma
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
# Disabled in test target only:
#  - untyped_error_in_catch
#  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
#  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
#  - vertical_whitespace
# - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
# - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
#  - explicit_self 
  - unused_declaration
  - unused_import


# Configurable Rules
identifier_name:
  min_length: 3 # only min_length
  allowed_symbols: "_"
  excluded: # excluded via string array
    - id
    - vc
    - nc
    - mo
    - dx
    - on
type_name:
  min_length: 3
  max_length: 60
  allowed_symbols: "_"
trailing_comma:
  mandatory_comma: true
line_length:
  warning: 150
  error: 180
  ignores_urls: true
  ignores_interpolated_strings: true
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - final
    - dynamic
    - required
    - convenience
    - override
    - lazy
    - owned
    - typeMethods
    - mutators
excluded:
  - Neptune/Teams/TripBooking/Services/Booking/Protobuf/http_v5_16.Booking.pb.swift
  - Neptune/Teams/TripBooking/Services/Booking/Protobuf/iot_v1_4.Booking.pb.swift
  - Neptune/Teams/TripBooking/Services/Booking/Protobuf/location_v1_0.Booking.pb.swift
  - Neptune/Teams/TripBooking/Services/Booking/Protobuf/route_v1_0.Booking.pb.swift
  - Neptune/Teams/Coupons/Services/Protobuf/http_v1_1.Coupons.pb.swift
  - Neptune/Teams/Payment/Services/DriverTipping/Protobuf/http_v1_1.DriverTipping.pb.swift
  - Neptune/Teams/Payment/Services/Payment/Protobuf/http_v1_7.Payment.pb.swift
  - Neptune/Teams/Payment/Services/Payment/Protobuf/selection_v1_3.Payment.pb.swift
  - Neptune/Teams/Payment/Services/Payment/Protobuf/verification_v1_3.Payment.pb.swift
  - Neptune/Teams/Payment/Services/BillingAddress/Protobuf/http_v1_1.BillingAddress.pb.swift
  - Neptune/Teams/Payment/Services/InvoiceNote/Protobuf/http_v1_2.InvoiceNote.pb.swift
  - Neptune/Teams/Customer/Services/Customer/Protobuf/customer_v1_5.Auth.pb.swift
  - Neptune/Teams/Customer/Services/TripHistory/Protobuf/http_v1_1.TripHistory.pb.swift
  - Neptune/Teams/Platform/Services/ServiceArea/Protobuf/servicecontext_v1_0.ServiceArea.pb.swift
  - Neptune/Teams/Platform/Services/ServiceArea/Protobuf/http_v1_0.ServiceArea.pb.swift
  - Neptune/Teams/Platform/Core/Util/Network/SharedProtos/unprocessableentity_v1_0.Shared.pb.swift
  - Neptune/Teams/Platform/Core/Util/Network/SharedProtos/emptymessage_v1_0.pb.swift
  - Neptune/Teams/Platform/Core/UserInterface/PaintCode/PCStyleKit.swift
  - TestSupport/Util/SnapshotTestCase/FBSnapshotTestCase/SwiftSupport.swift
  - Neptune/Teams/TripBooking/Services/TripSuggestions/Protobuf/http_v1_1.TripSuggestions.pb.swift
  - Neptune/Teams/Customer/Services/CustomerFeedback/Protobuf/http_v1_2.TripFeedback.pb.swift
  - Pods
